jks = [
    {  url : "https://jx.yparse.com/index.php?url=" , title : "Interface: Cloud Analysis"  } ,
    { title: "qqwtt", url: "https://jx.qqwtt.com/?url=" },
    { title: "剖元", url: "https://www.pouyun.com/?url=" },
    {  url : "https://jx.m3u8.tv/jiexi/?url=" , title : "Interface No. 5"  } ,
    {  url : "https://z1.m1907.top/?jx=" , title : "Have fun - 28-If the interface fails, please give feedback! QQ group: 237111082"  } ,
    { title: "eptept", url: "https://dmjx.m3u8.tv/?url=" },
    { title: "BL", url: "https://vip.bljiex.com/?v=" },
    { url: "https://www.mtosz.com/m3u8.php?url=", title: "Mao解析" },
    {  url : "https://jx.xmflv.com/?url=" , title : "Xiami Analysis"  } ,
    {  title : "Night" , url : "https://www.yemu.xyz/?url="  } ,
    {  title : "TV Analysis [Tencent (Mango)]" , url : "https://jx.m3u8.tv/jiexi/?url="  } ,
    { title: "冰豆", url: "https://api.qianqi.net/vip/?url=" },

    {  title : "人人analytics" , url : "https://vip.mpos.ren/v/?url="  } ,
    {  url : "http://vip.wandhi.com/?v=" , title : "Hi Analysis - 45-If the interface fails, please give feedback! QQ group: 237111082"  } ,
    { title : "Xiaomi" ,   url : "https://jx.xmflv.com/?url=" } ,
    {title: "yparse", "type": "1,2", url: "https://jx.yparse.com/index.php?url="},
    {title: "m1907", "type": "1,2", url: "https://im1907.top/?jx="},
    {title: "qianqi",  url: "https://api.qianqi.net/vip/?url="},
    { title : "Hi Analysis" ,   url : "https://t1.qlplayer.cyou/player/?url=" } ,
];
