jks = [
    { url: "https://jx.yparse.com/index.php?url=", title: "接口:云析" },
    { title: "qqwtt", url: "https://jx.qqwtt.com/?url=" },
    { title: "剖元", url: "https://www.pouyun.com/?url=" },
    { url: "https://jx.m3u8.tv/jiexi/?url=", title: "⑤号接口" },
    { url: "https://z1.m1907.top/?jx=", title: "玩的嗨——28-若接口失效可反馈！QQ群:237111082" },
    { title: "eptept", url: "https://dmjx.m3u8.tv/?url=" },
    { title: "BL", url: "https://vip.bljiex.com/?v=" },
    { url: "https://www.mtosz.com/m3u8.php?url=", title: "Mao解析" },
    { url: "https://jx.xmflv.com/?url=", title: "虾米解析" },
    { title: "夜幕", url: "https://www.yemu.xyz/?url=" },
    { title: "TV解析[腾讯 (芒果)]", url: "https://jx.m3u8.tv/jiexi/?url=" },
    { title: "冰豆", url: "https://api.qianqi.net/vip/?url=" },

    { title: "人人解析", url: "https://vip.mpos.ren/v/?url=" },
    { url: "https://vip.wandhi.com/?v=", title: "嗨解析——45-若接口失效可反馈！QQ群:237111082" },
    {title: "虾米",  url: "https://jx.xmflv.com/?url="},
    {title: "yparse", "type": "1,2", url: "https://jx.yparse.com/index.php?url="},
    {title: "m1907", "type": "1,2", url: "https://im1907.top/?jx="},
    {title: "qianqi",  url: "https://api.qianqi.net/vip/?url="},
    {title: "嗨解析",  url: "https://t1.qlplayer.cyou/player/?url="},
];
